services:
  postgres:
    image: postgres:17-alpine
    container_name: meetup-db
    environment:
      POSTGRES_DB: meetup_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
